name = "Dragonrealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62dc45bc2a93854ab77a8877d96ace0baef5259ffb5aa8394793f61feddefc89"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
