name = "Dragonrealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68d0cd56753554e9a9683aab90d5ba65d295dbb2c72c678c4df71cc654cdb8d6"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
