name = "Dragonrealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9a66927c643c1aeafe97ebe431b2a969986b9a91408d59848b884b620f6276b"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
