name = "DragonRealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb283835ec8457b3ed9dfc39bdb27bc39baa34d0e21e1427e418bbe032c11571"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.0.1"
