name = "Dragonrealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b894a7211f32b57765f595076c83b8393144a5fe244cb9ae792227f0980d6876"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
