name = "Dragonrealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07fe0ea30a6b6b4c19d071264bce9b91a4502bf14b05c9f16277ae440cdf9a15"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.0.1"
