name = "Dragonrealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "056c62693a4c63a6f2c7653701bf8559fffd7dc3699e6844b4e9743409218b9c"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.0.1"
