[flavor_groups.betterfoliage]
name = "Better Foliage"
description = "Adds bushy leaves, grassy grass blocks, falling leaf particles, algae and more. Highly configurable, anything can be disabled. Client only."
side = "client"
[[flavor_groups.betterfoliage.choices]]
id = "yes_betterfoliage"
name = "Yes"
description = "Installs Better Foliage."
[[flavor_groups.betterfoliage.choices]]
id = "no_betterfoliage"
name = "No"
description = "Do not install Better Foliage."

[flavor_groups.dualhotbar]
name = "Dual Hotbar"
description = "Makes the top row of your inventory (can be changed) into a fully functional extra hotbar, by default on top of your normal hotbar (9 columns, two rows), but can be configured into an 18-slot long hotbar. Client grants partial functionality (hotbar slot swapping), if on server as well then full functionality."
side = "both"
[[flavor_groups.dualhotbar.choices]]
id = "yes_dualhotbar"
name = "Yes"
description = "Installs Dual Hotbar."
[[flavor_groups.dualhotbar.choices]]
id = "no_dualhotbar"
name = "No"
description = "Do not install Dual Hotbar."

[flavor_groups.dynamicsurroundings ]
name = "Dynamic Surroundings"
description = "Adds various sounds based on what you are doing and what is happening around and to you as well as an aurora in the sky at night. Can also be used to block out *any* sound. Client only."
side = "client"
[[flavor_groups.dynamicsurroundings.choices]]
id = "yes_dynamicsurroundings"
name = "Yes"
description = "Installs Dynamic Surroundings."
[[flavor_groups.dynamicsurroundings.choices]]
id = "no_dynamicsurroundings "
name = "No"
description = "Do not install Dynamic Surroundings ."

[flavor_groups.litemods]
name = "Litemods"
description = "Installs LiteLoader and your choice of litemods. All client only."
side = "client"
[[flavor_groups.litemods.choices]]
id = "voxelmap"
name = "Voxelmap"
description = "Installs LiteLoader and Voxelmap, a mini/world map mod. Recommended."
[[flavor_groups.litemods.choices]]
id = "worldeditcui"
name = "WorldEdit CUI"
description = "Installs LiteLoader and WorldEdit CUI, which shows your WorldEdit selection."
[[flavor_groups.litemods.choices]]
id = "yes_litemods"
name = "Both"
description = "Installs LiteLoader, Voxelmap and WorldEdit CUI."
[[flavor_groups.litemods.choices]]
id = "no_litemods"
name = "None"
description = "Do not install LiteLoader or any litemods."

[flavor_groups.tyksera]
name = "Tyksera"
description = "Reika's 1.7.10 resourcepack made from a mixture of vanilla textures,  custom textures and recombinated textures from other packs such as Faithful 32x, Sphax and Adventure Island. Only downloads Tyksera, does not enable it. It can also be found at https://dragonrealm.overminddl1.com/texture.php for later installs."
side = "client"
[[flavor_groups.tyksera.choices]]
id = "yes_tyksera"
name = "Yes"
description = "Downloads Tyksera."
[[flavor_groups.tyksera.choices]]
id = "no_tyksera"
name = "No"
description = "Do not download Tyksera."

[flavor_groups.chameleoncreepers]
name = "Chameleon Creepers "
description = "Shifts the hue of creepers to match their surroundings, giving them camouflage like they originally had. Client only."
side = "client"
[[flavor_groups.chameleoncreepers.choices]]
id = "yes_chameleoncreepers"
name = "Yes"
description = "Installs Chameleon Creepers."
[[flavor_groups.chameleoncreepers.choices]]
id = "no_chameleoncreepers"
name = "No"
description = "Do not install Chameleon Creepers."

[flavor_groups.soundfilters]
name = "Sound Filters"
description = "Adds reverb to caves and underwater/covered up muting. Client only."
side = "client"
[[flavor_groups.soundfilters.choices]]
id = "yes_soundfilters"
name = "Yes"
description = "Installs Sound Filters."
[[flavor_groups.soundfilters.choices]]
id = "no_soundfilters"
name = "No"
description = "Do not install Sound Filters."


[flavor_groups.optifine]
name = "Optifine"
description = "Install Optifine?."
side = "client"
[[flavor_groups.optifine.choices]]
id = "no"
name = "No"
description = "Does not install Optifine."
[[flavor_groups.optifine.choices]]
id = "godsno"
name = "Hell no"
description = "Does not install Optifine, why are you even asking this?"

[metafile.better-foliage]
flavors = "yes_betterfoliage"
[metafile.dual-hotbar]
flavors = "yes_dualhotbar"
[metafile.dynamic-surroundings]
flavors = "yes_dynamicsurroundings"
[metafile.liteloader]
flavors = ["voxelmap, worldeditcui, yes_litemods"]
[metafile.voxelmap-litemod]
flavors = ["voxelmap, yes_litemods"]
[metafile.worldeditcui-litemod]
flavors = ["worldeditcui, yes_litemods"]
[metafile.tyksera]
flavors = "yes_tyksera"
[metafile.chameleoncreepers]
flavors = "yes_chameleoncreepers"
[metafile.sound-filters]
flavors = "yes_soundfilters"